INSERT INTO libros (id, nombre, autor, tipo, cantidad_libros) VALUES (1, 'El código da Vinci', 'Dan Brown', 'Novela de misterio', 29);
INSERT INTO libros (id, nombre, autor, tipo, cantidad_libros) VALUES (2, 'El señor de los anillos', 'J.R.R.Tolkien', 'Fantasía', 19);
INSERT INTO libros (id, nombre, autor, tipo, cantidad_libros) VALUES (3, 'El Principito', 'Antoine de Saint-Exupéry', 'Novela filosófica', 24);
INSERT INTO libros (id ,nombre, autor, tipo, cantidad_libros) VALUES (4, 'Don Quijote de la Mancha', 'Miguel de Cervantes', 'Novela de aventuras', 34);
INSERT INTO libros (id, nombre, autor, tipo, cantidad_libros) VALUES (5, 'El diario de Ana Frank', 'Ana Frank', 'Autobiografía', 17);
INSERT INTO libros (id, nombre, autor, tipo, cantidad_libros) VALUES (6, 'El Alquimista', 'Paulo Coelho', 'Fábula', 27);
INSERT INTO libros (id, nombre, autor, tipo, cantidad_libros) VALUES (7, 'Harry Potter y la piedra filosofal', 'J.K: Rowling', 'Novela fantástica', 22);
INSERT INTO libros (id, nombre, autor, tipo, cantidad_libros) VALUES (8, 'Cien años de soledad', ' Gabriel García Márquez', 'Realismo mágico', 39);
INSERT INTO libros (id, nombre, autor, tipo, cantidad_libros) VALUES (9, 'El nombre de la rosa', 'Umberto Eco', 'Novela histórica de misterio', 19);
INSERT INTO libros (id, nombre, autor, tipo, cantidad_libros) VALUES (10, 'Historia de dos ciudades', 'Charles Dickens', 'Novela histórica', 29);
INSERT INTO libros (id, nombre, autor, tipo, cantidad_libros) VALUES (11, 'Crepúsculo', 'Stephenie Meyer', 'Novela', 12);
INSERT INTO libros (id, nombre, autor, tipo, cantidad_libros) VALUES (12, 'El hombre en busca de sentido', 'Viktor Frankl', 'Relato autobiográfico', 159);
INSERT INTO libros (id, nombre, autor, tipo, cantidad_libros) VALUES (13, 'La sombra del viento', 'Carlos Ruiz Zafón', 'Novelas de prosa', 89);
INSERT INTO libros (id, nombre, autor, tipo, cantidad_libros) VALUES (14, 'Piense y hágase rico', 'Napoleón Hill', 'Autoayuda', 109);
INSERT INTO libros (id, nombre, autor, tipo, cantidad_libros) VALUES (15, 'Luces de bohemia', 'Ramón del Valle-Inclán', 'Obra teatral', 79);
INSERT INTO libros (id, nombre, autor, tipo, cantidad_libros) VALUES (16, 'Crimen y castigo', 'Gabriel García Márquez', 'Novela', 149);
INSERT INTO libros (id, nombre, autor, tipo, cantidad_libros) VALUES (17, 'La casa de los espíritus', 'Isabel Allende', 'Realismo mágico', 79);
INSERT INTO libros (id, nombre, autor, tipo, cantidad_libros) VALUES (18, 'Preludio a la fundación', 'Isaac Asimov', 'Novela de ciencia ficción', 119);
INSERT INTO libros (id, nombre, autor, tipo, cantidad_libros) VALUES (19, 'Las almas muertas', 'Nicolai Gogol', 'Poema épico', 59);
INSERT INTO libros (id, nombre, autor, tipo, cantidad_libros) VALUES (20, 'La comedia humana', 'Honoré de Balzac', 'Novela', 69);
INSERT INTO usuarios (id, nombre, apellido, email, cantidad_prestamos) VALUES (1, 'Luis', 'García', 'luisgarcia@example.com', 10);
INSERT INTO usuarios (id, nombre, apellido, email, cantidad_prestamos) VALUES (2, 'María', 'Aranda', 'mariaaranda@example.com', 25);
INSERT INTO usuarios (id, nombre, apellido, email, cantidad_prestamos) VALUES (3,'Karola', 'Martínez', 'karolamartinez@example.com', 15);
INSERT INTO usuarios (id, nombre, apellido, email, cantidad_prestamos) VALUES (4, 'Martín', 'López', 'martinlopez@example.com', 45);
INSERT INTO usuarios (id, nombre, apellido, email, cantidad_prestamos) VALUES (5, 'Alejandro', 'González', 'alegonzalez@example.com', 8);
INSERT INTO usuarios (id, nombre, apellido, email, cantidad_prestamos) VALUES (6, 'Lucía', 'Castro', 'luciacastro@example.com', 30);
INSERT INTO usuarios (id, nombre, apellido, email, cantidad_prestamos) VALUES (7, 'Alberto', 'Márquez', 'albertomarquez@example.com', 12);
INSERT INTO usuarios (id, nombre, apellido, email, cantidad_prestamos) VALUES (8, 'Javier', 'Fernández', 'javierfer@example.com', 18);
INSERT INTO usuarios (id, nombre, apellido, email, cantidad_prestamos) VALUES (9, 'Daniela', 'Sánchez', 'danielasan@example.com', 5);
INSERT INTO usuarios (id, nombre, apellido, email, cantidad_prestamos) VALUES (10, 'Marta', 'Rodríguez', 'martaro@example.com', 22);
